Дана матрица целых чисел А. Полагаем, что число в последней строке последнего столбца "испорчено". Восстановить значение в ячейке таблицы с помощью коэффициента корреляции столбцов (с помощью формулы с лекции)

In [46]:
import numpy as np
import math

def s(P):
    n = np.size(P,0)

    meanP = P.mean()

    #print(P)
    #print(meanP)
    #print(n)

    sumP = 0

    for i in P:
        sumP += (i - meanP) * (i - meanP)    

    #print(sumP)

    return math.sqrt(1/(n-1) * sumP)


def KK(P, Q):
    n = np.size(P,0)

    #print(P)
    #print(Q)
    #print(n)

    meanP = P.mean()
    meanQ = Q.mean()

    #print(meanP)
    #print(meanQ)

    sumPQ = 1

    for i in range(0,n):
        sumPQ += P[i] * Q[i]

    #print(sumPQ)

    sP = s(P) #Неэффективно это каждый раз пересчитывать
    sQ = s(Q)

    #print(sP)
    #print(sQ)

    #print(((sumPQ - n * meanP * meanQ) / ((n - 1) * sP * sQ)))
    return ((sumPQ - n * meanP * meanQ) / ((n - 1) * sP * sQ))


def restore_last_elem(A):
    
    s = np.size(A, 0)
    c = np.size(A, 1)
    
    print(A)

    a = np.delete(A, -1, 0)

    #print(a)

    bad_col = a[:,-1]
    bad_row = A[-1,:]

    print("Плохая строка")
    print(bad_row)

    array_KK = np.zeros(c - 1,float)

    mean_bad_col = bad_col.mean()

    mean_a = np.zeros(c - 1,float)

    for i in range(0,c - 1):
        array_KK[i] = KK(bad_col, a[:,i])
        mean_a[i] = a[:,i].mean()

    print("КК")
    print(array_KK)
    print("Средние кроме последнего столбца")
    print(mean_a)

    up = 0
    down = 0

    for i in range(0,c - 1):
        up += array_KK[i] * (A[-1][i] - mean_a[i])

    for i in array_KK:
        down += math.fabs(i)

    result = mean_bad_col + up / down

    print("Результат")
    print(result)

    A[-1][-1] = result 

    #print(A)
    
    return A


example_from_lecture = np.array([[99,56,91,160,58],[89,58,89,157,48],[91,64,91,165,54],[91,51,91,170,54],[86,56,84,157,44],[97,53,86,175,56],[94,51,91,165,54]])
example_random = np.random.randint(0, 10, size = (10,10))

print("Пример из лекции")
print(restore_last_elem(example_from_lecture))
print("Пример случайного массива")
print(restore_last_elem(example_random))



Пример из лекции
[[ 99  56  91 160  58]
 [ 89  58  89 157  48]
 [ 91  64  91 165  54]
 [ 91  51  91 170  54]
 [ 86  56  84 157  44]
 [ 97  53  86 175  56]
 [ 94  51  91 165  54]]
Плохая строка
[ 94  51  91 165  54]
КК
[ 0.91455084 -0.11501618  0.62492611  0.61127269]
Средние кроме последнего столбца
[ 92.16666667  56.33333333  88.66666667 164.        ]
Результат
54.25741998260628
[[ 99  56  91 160  58]
 [ 89  58  89 157  48]
 [ 91  64  91 165  54]
 [ 91  51  91 170  54]
 [ 86  56  84 157  44]
 [ 97  53  86 175  56]
 [ 94  51  91 165  54]]
Пример случайного массива
[[9 9 4 3 7 0 8 6 0 1]
 [9 2 3 2 4 9 4 7 9 7]
 [3 1 2 3 9 1 6 1 6 1]
 [9 4 4 8 5 2 6 9 3 2]
 [4 5 7 4 3 0 7 2 2 8]
 [5 8 5 6 5 5 0 3 0 5]
 [2 2 3 7 5 1 8 0 6 1]
 [1 6 2 1 1 8 6 6 5 4]
 [9 5 2 7 6 9 2 2 1 8]
 [0 9 8 8 2 1 2 0 8 2]]
Плохая строка
[0 9 8 8 2 1 2 0 8 2]
КК
[ 0.23870132  0.09576924  0.30920827 -0.04223833 -0.43376642  0.58710436
 -0.51941729 -0.02687154 -0.07357525]
Средние кроме последнего столбца
[5.66666667 4.6

Найти в заданной матрице целых чисел А все строки в которых есть хотябы один 0. Удалить такие строки из матрицы.

In [9]:
import numpy as np #Это каждый раз писать не надо, но я каждую задачу писал и запускал отдельно

s = 10
c = 8

A = np.random.randint(0, 10, size = (s,c))

'''
Наверно все это можно сделать красиво через np.delete() ,но у меня получлось только строки состоящие из нулей удалять
Так что сделал как обычно бы
'''

origin_A = A

print(origin_A)

def index_row_with_zero(a):
    for i in range(0,np.size(a,0)):
        for j in range(0,np.size(a,1)):
            if a[i][j] == 0:
                return i
    return -1
    
index = index_row_with_zero(A)

while index != -1:
    A = np.delete(A, index, 0)
    index = index_row_with_zero(A)

print(A)

[[3 7 0 8 6 4 8 4]
 [1 1 6 5 5 0 4 6]
 [7 3 2 7 1 5 9 2]
 [9 3 8 4 9 0 9 1]
 [5 1 2 7 3 6 2 6]
 [5 0 1 0 6 7 9 0]
 [7 8 3 4 8 9 6 9]
 [4 5 4 6 0 7 3 6]
 [7 9 1 6 4 0 4 3]
 [3 6 6 7 8 6 2 3]]
[[7 3 2 7 1 5 9 2]
 [5 1 2 7 3 6 2 6]
 [7 8 3 4 8 9 6 9]
 [3 6 6 7 8 6 2 3]]


Дана матрица целых чисел А. Для каждого ее столбца найти среднее арифметическое всех ненулевых элементов. ЗАменить все 0 в матрице на полученное ранее среднее значение (для каждого столбца оно своё).

In [42]:
import numpy as np

s = 10
c = 8

A = np.random.randint(0, 10, size = (s,c))

means = np.zeros(c,float)

print(A)

for i in range(0,c):
    a = A[:,i] #Так достаем стольбцы
    means[i] = a.mean()
    
print(means)

'''Можно в один цикл всё сделать'''
for i in range(0,c):
    for j in range(0,s):
        if A[j][i] == 0:
            A[j][i] = means[i]
            
print(A)

[[2 1 6 8 9 3 8 8]
 [3 8 5 6 7 8 5 6]
 [1 7 9 4 8 9 5 7]
 [1 3 8 6 6 5 6 6]
 [1 2 2 3 8 7 0 9]
 [6 1 6 4 0 3 2 7]
 [6 9 8 4 3 6 5 5]
 [1 6 8 9 4 1 7 5]
 [9 8 6 2 9 4 8 2]
 [3 9 0 5 1 4 1 6]]
[3.3 5.4 5.8 5.1 5.5 5.  4.7 6.1]
[[2 1 6 8 9 3 8 8]
 [3 8 5 6 7 8 5 6]
 [1 7 9 4 8 9 5 7]
 [1 3 8 6 6 5 6 6]
 [1 2 2 3 8 7 4 9]
 [6 1 6 4 5 3 2 7]
 [6 9 8 4 3 6 5 5]
 [1 6 8 9 4 1 7 5]
 [9 8 6 2 9 4 8 2]
 [3 9 5 5 1 4 1 6]]
